apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.server.name }}
  labels:
    app_name: {{ .Chart.Name }}
    app_version: {{ .Values.server.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  {{- if .Values.server.installPlugins }}
  grafana-install-plugins: {{ .Values.server.installPlugins | quote }}
  {{- end }}
  grafana.ini: |
{{- include "grafana.ini.tpl" . | indent 4 -}}