apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.server.persistentVolume.storageClass | quote }}
  {{- if .Values.server.persistentVolume.annotations }}
{{ toYaml .Values.server.persistentVolume.annotations | indent 4 }}
  {{- end }}
  labels:
    app_name: {{ .Values.server.name }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Values.server.name }}
spec:
  accessModes:
{{- range .Values.server.persistentVolume.accessModes }}
    - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.server.persistentVolume.size | quote }}