apiVersion: v1
kind: Secret
metadata:
  labels:
    app_name: {{ .Values.server.name }}
    app_version: {{ .Values.server.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Values.server.name }}
type: Opaque
data:
  grafana-admin-password: {{ .Values.server.adminPassword | b64enc | quote }}
  grafana-admin-user: {{ .Values.server.adminUser | b64enc | quote }}