apiVersion: v1
kind: Service
metadata:
  labels:
    app_name: {{ .Values.server.name }}
    app_version: {{ .Values.server.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Values.server.name }}
spec:
  selector:
    app_name: {{ .Values.server.name }}
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 3000