apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.alertmanager.name }}
  labels:
    app_name: {{ .Values.alertmanager.name }}
    app_version: {{ .Values.alertmanager.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - host: {{ .Values.alertmanager.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.alertmanager.name }}
          servicePort: 80