apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app_name: {{ .Values.alertmanager.name }}
    app_version: {{ .Values.alertmanager.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: {{ .Values.alertmanager.name }}
data:
  alertmanager.yml: |
{{- include "alertmanager.yml.tpl" . | indent 4 -}}