kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.nodeExporter.name }}
  labels:
    app_name: {{ .Values.nodeExporter.name }}
    app_version: {{ .Values.nodeExporter.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app_name: {{ .Values.nodeExporter.name }}
  template:
    metadata:
      labels:
        app_name: {{ .Values.nodeExporter.name }}
        node_exporter_version: {{ .Values.nodeExporter.image.tag | quote }}
        helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      containers:
      - name: {{ .Values.nodeExporter.name }}
        args:
          - --collector.procfs=/host/proc
          - --collector.sysfs=/host/sys
        {{- range $key, $value := .Values.nodeExporter.extraArgs }}
          - --{{ $key }}={{ $value }}
        {{- end }}
        ports:
          - containerPort: 9100
            hostPort: 9100
            name: metrics
        resources:
{{ toYaml .Values.nodeExporter.resources | indent 10 }}
        image: {{ .Values.nodeExporter.image.repository }}/{{ .Values.nodeExporter.image.name }}:{{ .Values.nodeExporter.image.tag }}
        imagePullPolicy: "{{ .Values.nodeExporter.image.pullPolicy }}"
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly:  true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: system-bus-socket
          mountPath: /var/run/dbus/system_bus_socket
          readOnly: true
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 10
          httpGet:
            path: "/metrics"
            port: 9100
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: "/metrics"
            port: 9100
      hostNetwork: true
      hostPID: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: system-bus-socket
        hostPath:
          path: /var/run/dbus/system_bus_socket
