apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.server.name }}
  labels:
    app_name: {{ .Chart.Name }}
    app_version: {{ .Values.server.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  prometheus.yml: |
{{- include "prometheus.yml.tpl" . | indent 4 }}
  alerts: |
{{ (.Files.Get "prometheus-rules/alerts.txt") | indent 4 }}