apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app_name: {{ .Values.name }}
    app_version: {{ .Values.image.tag | quote }}
    helm_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app_name: {{ .Values.name }}
  ports:
    - name: "http"
      port: 80
      protocol: TCP
      targetPort: 8080